"""
Django settings for resource_server project.

Generated by 'django-admin startproject' using Django 2.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 't&%bj3g@ugju!b$e@%nt99$^52x5=+1)z6$mfkn6s+(uur8o4x'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'resource_server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'resource_server.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

AUTHENTICATION_BACKENDS = [
    'resource_server.resource_server.KeycloakBackend',
]
LOGIN_URL = 'login'
# Keycloak settings
KEYCLOAK_CLIENT_ID = 'test'
KEYCLOAK_CLIENT_SECRET = 'bb407cfe-0328-4e3e-952c-c338a4361fb5'
KEYCLOAK_AUTHORIZE_URL = 'http://localhost:9000/auth/realms/master/protocol/openid-connect/auth'
KEYCLOAK_TOKEN_URL = 'http://localhost:9000/auth/realms/master/protocol/openid-connect/token'
KEYCLOAK_USERINFO_URL = 'http://localhost:9000/auth/realms/master/protocol/openid-connect/userinfo'
KEYCLOAK_PUBLIC_KEY = """-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhFFnTfNitQXyA3mBd6ShmzyrFdCbbPzbqmzr4/Rx83QzIRpMgQup+y+SL5/Xc10BunMrH886NA/3w2GLKaGiimPsAqCMasv6VaoZBd/TtGFKvWkWhkVbqOAPKTle2d7cTf2yehAWb3Y/I2gPvflcOmMdH3SEmhpfqDioLWIb/R6yd752wGl7lHooyGPGi9TF/yyUrfyRKj7BivpzHEkz2GrkKF10gzGTdevTPTpD0qxYVoEquMJdqvjqa/2Bwx/korYZYBytENBp8bkmSqB5YoNLqSBL1yZgPsfMSax6tVal560DjOL732ZcHiFTr7gftsrbn4ksWxr9W8ZcC3CPDwIDAQAB\n-----END PUBLIC KEY-----"""


# for python social auth
# PUBLIC_KEY = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhFNMmPdOa9c+exhND9CvZREoOUIfs0b2Dv9/RDKWQjC9CmS0+oJ5R1joJAVSJL4G3N0U62On6QVkTaqFcj5MdQzmhxFA5JTkoTJA4j/9Fmvn3OJaotjsT28cnLI6K8Noabf04A9+zsR4QORSXE4XtxmfLBCWuLRY+GbxvX6j9tAT18who6M4gUzbyMq7NancIsVoNb1bDq1MN7rGl/DL+TEC494F3md0w48XhwGzaLfj+zuTWC+PTilh/abe48v67HCnNIFVLEMLzYJ/S+6aYD+5hJoET7pRS9qzGbyRMVP9CAShs2WVc1keFDwSV7+swpIc2c6Nhft52IrCi89fewIDAQAB'

LOGGING = {
    'version': 1,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'resource_server': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'INFO'
        },
    },
}